### ISSUE TITLE
Can't find Test-FileExtension

### ISSUE THREAD

**Issue by hoagsie** [adbertram/PSWebDeploy#1]
Hi,

I get the following:

> Sync-Website : Cannot validate argument on parameter 'SourcePackage'. The term 'Test-FileExtension' is not recognized as the name of a cmdlet, function, script file, 
> or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

It looks like this is a dependency that isn't packaged. What module should I be installing to get this function?

**Comment by adbertram** [comment]
This reference has been removed now.
